# Generated by Django 3.0.8 on 2021-02-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210226_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liked_by', to='network.Post'),
        ),
    ]
