# Generated by Django 3.0.8 on 2021-02-26 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20210226_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked_posts',
        ),
        migrations.AddField(
            model_name='user',
            name='likedPosts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liked_by', to='network.Post'),
        ),
    ]
