# Generated by Django 3.0.8 on 2021-03-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20210305_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
